language: php

php:
  - nightly
  - 7.1
  - 7
  - 5.6
  - 5.5

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

env:
  - PACKAGES='symfony/symfony=~3.4@dev'
  - PACKAGES='symfony/symfony=3.3.*'
  - PACKAGES='symfony/symfony=3.2.*'
  - PACKAGES='symfony/symfony=2.8.*'
  - PACKAGES='symfony/symfony=2.7.*'

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: PACKAGES='symfony/symfony=~4.0@dev' STABILITY=dev
    - php: nightly
      env: PACKAGES='symfony/symfony=~4.0@dev' STABILITY=dev

  allow_failures:
    - php: nightly
    - env: PACKAGES='symfony/symfony=~4.0@dev' STABILITY=dev

before_install:
  - travis_retry composer self-update

install:
  - composer require --no-update ${PACKAGES}
  - if [ "$STABILITY" = "dev" ]; then composer config minimum-stability dev; fi;
  - composer --prefer-source install

script:
  - rm -rf build
  - mkdir -p build
  - vendor/bin/phpunit --colors -c phpunit.xml
  - JMS_BUNDLE=1 vendor/bin/phpunit --colors -c phpunit.xml
  - JMS_BUNDLE=1 DOCTRINE_BUNDLE=1 vendor/bin/phpunit --colors -c phpunit.xml
