language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - nightly
  - hhvm

env:
  - PACKAGES='symfony/symfony=2.7.*' deps='no'
  - PACKAGES='symfony/symfony=2.8.*' deps='no'
  - PACKAGES='symfony/symfony=3.2.*' deps='no'
  - PACKAGES='symfony/symfony=3.3.*' deps='no'
  - PACKAGES='symfony/symfony=~3.4@dev' deps='no'

matrix:
    include:
      - php: 5.5
        env: PACKAGES='symfony/symfony=2.7.*' deps='low'
      - php: 7.1
        env: PACKAGES='symfony/symfony=~4.0@dev sensio/framework-extra-bundle=~4.0@dev' deps='no'
      - php: nightly
        env: PACKAGES='symfony/symfony=~4.0@dev sensio/framework-extra-bundle=~4.0@dev' deps='no'

    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - composer require --no-update ${PACKAGES}
  - if [ "$deps" = "no" ] || [ -z "$deps" ]; then composer --prefer-source install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-source --prefer-lowest --prefer-stable update; composer --prefer-source install; fi;

script:
  - rm -rf build
  - mkdir -p build
  - vendor/bin/phpunit --colors -c phpunit.xml
  - JMS_BUNDLE=1 vendor/bin/phpunit --colors -c phpunit.xml
  - JMS_BUNDLE=1 DOCTRINE_BUNDLE=1 vendor/bin/phpunit --colors -c phpunit.xml
